name: CI/CD Acal-Left

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-pack-windows:
    name: Build & Pack Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Create Windows Installer (jpackage)
        shell: pwsh
        run: |
          $RAW_VERSION = "${{ github.ref_name }}"
          $CLEAN_VERSION = $RAW_VERSION -replace '^v', ''
          
          echo "Versão original: $RAW_VERSION"
          echo "Versão limpa para Windows: $CLEAN_VERSION"
  
          jpackage --type exe `
            --dest dist/ `
            --name "AcalLeft" `
            --input acal-left-app/target/ `
            --main-jar acal-left-app-0.0.1-SNAPSHOT.jar `
            --main-class acal.com.acal_left.AcalLeftApplication `
            --win-shortcut `
            --win-menu `
            --vendor "Alexandre" `
            --app-version $CLEAN_VERSION `
            --verbose

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: acal-left-windows-exe
          path: dist/*.exe



  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build-and-pack-windows
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/acal-left-windows-exe/*.exe